language: node_js
node_js:
    - "0.10"
services:
    - couchdb
env:
    global:
        - NODE_ENV=test
    matrix:
        - VERSION=0.8.9
        - VERSION=0.8.21
        - VERSION=0.8.18
        - VERSION=0.10
        - VERSION=0.8
before_install:
    - npm install n coffee-script -g
    - n $VERSION
    - node --version
